# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.19.0, 22.x, 24.x]

        steps:
            -   uses: actions/checkout@v4

            -   name: Install package manager (from package.json)
                run: |
                    corepack enable
                    corepack install

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: yarn
            -   run: yarn install
            -   run: yarn audit
            -   run: yarn build
#            -   run: yarn test todo, no tests yet
